version: '3.8'

services:
  face-recognition:
    build: .
    container_name: face-recognition
    ports:
      - "8000:8000"
    volumes:
      - ./employee_images:/app/employee_images
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: face_recognition
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped